---
- name: Restart chasquid
  systemd:
    name: chasquid
    state: restarted

- name: Reload chasquid
  systemd:
    name: chasquid
    state: reloaded

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Reboot system
  reboot:
    reboot_timeout: 600
    msg: "Rebooting system after IPv6 configuration changes"
