alicloud_dns_sync_domain: "svc.plus"
alicloud_dns_sync_records:
  - rr: www
    type: A
    value: 1.1.1.1
    ttl: 600

  - rr: api
    type: A
    value: 2.2.2.2

  - rr: mx
    type: MX
    value: mail.svc.plus
    ttl: 300
