zot_version: v2.1.11
zot_binary_url: "https://github.com/project-zot/zot/releases/download/{{ zot_version }}/zot-linux-amd64"
zot_binary_path: /usr/bin/zot
zot_user: zot
zot_group: zot
zot_data_dir: /data/zot
zot_log_dir: /var/log/zot
zot_config_dir: /etc/zot
zot_config_path: /etc/zot/config.json
zot_htpasswd_path: /etc/zot/htpasswd
zot_service_name: zot
zot_service_limits:
  nofile: 500000
  memory_high: 30G
  memory_max: 32G
zot_http_address: 0.0.0.0
zot_http_port: 5000
zot_tls_cert_path: ""
zot_tls_key_path: ""
zot_log_level: info
zot_sync_enabled: false
zot_sync_registries:
  - urls:
      - https://mirror.gcr.io/library
    onDemand: true
    maxRetries: 3
    retryDelay: 5m
    pollInterval: 6h
  - urls:
      - https://docker.io/library
    onDemand: true
zot_auth_users: []
zot_verify_config: false
