---
blackbox_version: "0.27.0"
blackbox_user: "blackbox"
blackbox_bin: "/usr/local/bin/blackbox_exporter"
blackbox_conf_dir: "/opt/blackbox"
blackbox_conf_file: "/opt/blackbox/blackbox.yml"
blackbox_listen: ":9115"
blackbox_arch_map:
  x86_64: linux-amd64
  amd64: linux-amd64
  aarch64: linux-arm64
  arm64: linux-arm64
blackbox_download_base_url: "https://dl.svc.plus/prometheus/blackbox_exporter"
blackbox_tmp_dir: "/tmp"
dl_business_host: "dl.svc.plus"
