---
# Default deployment directory for Zitadel Docker stack
zitadel_deploy_dir: /opt/zitadel
zitadel_workspace: "{{ zitadel_deploy_dir }}"
zitadel_domain: auth.svc.plus
zitadel_masterkey: MasterkeyNeedsToHave32Characters
