- name: setup OpenResty server
  hosts: global-homepage.svc.plus
  become: true
  vars:
      alicloud_dns_domain: "svc.plus"
      alicloud_dns_rr: "www"
      alicloud_dns_type: "A"
      alicloud_dns_value: "1.2.3.4"
      alicloud_access_key: "{{ aliyun_ak }}"
      alicloud_secret_key: "{{ aliyun_sk }}"
  roles:
    - role: vhosts/alicloud_dns_record
