- name: setup zitadel
  hosts: all
  become: true
  vars:
    zitadel_target_host: auth.svc.plus
    zitadel_domain: "{{ domain }}"
    zitadel_masterkey: MasterkeyNeedsToHave32Characters
    zitadel_workspace: /opt/zitadel
  roles:
    #- vhosts/common/
    - vhosts/docker/
    - docker/zitadel/
