---
- name: Ensure Alicloud DNS Record
  alicloud_dns_record:
    state: present
    domain: "{{ alicloud_dns_domain }}"
    rr: "{{ alicloud_dns_rr }}"
    type: "{{ alicloud_dns_type }}"
    value: "{{ alicloud_dns_value }}"
    ttl: "{{ alicloud_dns_ttl }}"
    priority: "{{ alicloud_dns_priority }}"
    access_key_id: "{{ alicloud_access_key }}"
    access_key_secret: "{{ alicloud_secret_key }}"
    security_token: "{{ alicloud_security_token }}"
  register: dns_result

- debug:
    var: dns_result
